"""empty message

Revision ID: 50af48b86c7a
Revises: 550fe1cd4985
Create Date: 2024-09-16 10:42:28.514817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50af48b86c7a'
down_revision = '550fe1cd4985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_slots')
    # ### end Alembic commands ###
